name: First Workflow
on: workflow_dispatch
jobs: 
  first-job: 
    runs-ons: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "hello world"
      - name: print goodbye
        run: echo "Done - bye!"
